### ISSUE TITLE
Jupyter can't see pyscript/scripts/ context, but can see pyscript/modules/ ones

### ISSUE THREAD

**Issue by dorbitbrown** [craigbarratt/hass-pyscript-jupyter#15]
My pyscript/scripts context has gone missing in Jupyter, making it very hard to debug code.  Un-installing and re-installing the shim has had no effect. 

In Jupyter, my list of available global contexts is correct, except for the missing script context:
`['jupyter_1', 'modules.dic_tools', 'modules.logit', 'modules.physics', 'modules.reports']`

If I try to switch to the  missing context the way I used to, I now get a NameError:
`Exception in <jupyter_1> line 1:
    pyscript.set_global_ctx('scripts.mkwd_main')
                            ^
NameError: global context 'scripts.mkwd_main' does not exist`

I'm not sure exactly what initiated the problem, although I suspect it started when I first added modules. 

Any suggestions? Thanks in advance!

**Comment by dorbitbrown** [comment]
Re-installing Anaconda including Jupyter took care of it

**Comment by craigbarratt** [comment]
Thanks for the follow up.  Glad it's working now.
