### ISSUE TITLE
SyntaxError kills kernel

### ISSUE THREAD

**Issue by basnijholt** [craigbarratt/hass-pyscript-jupyter#6]
Not sure if this is unexpected, but a SyntaxError results in a dying kernel and kernel restart:

![image](https://user-images.githubusercontent.com/6897215/91655620-2a1f6400-eab2-11ea-8809-72066b7bec5b.png)
![image](https://user-images.githubusercontent.com/6897215/91655638-4b805000-eab2-11ea-9807-1cd28da5e687.png)

**Comment by craigbarratt** [comment]
Oops. My last commit to pyscript broke that. I just pushed [this commit](https://github.com/custom-components/pyscript/commit/e1b1eefd3e10c5abdac9bcdafd094817d3a6dd19) to fix it. Adding tests to pyscript for the new jupyter kernel is on my todo list.
